version: '3.8'

services:
  # Tier 1: Frontend
  frontend:
    image: eklakalam/devops-tier3-frontend:latest
    container_name: production-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Next.js specific variable
      - NEXT_PUBLIC_API_URL=http://13.203.200.9:5000
    depends_on:
      - backend
    networks:
      - app-network

  # Tier 2: Backend
  backend:
    image: eklakalam/devops-tier3-backend:latest
    container_name: production-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database   # Must match the service name below
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD} # Matches your Node code (process.env.DB_PASS)
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  # Tier 3: Database
  database:
    image: mysql:8.0
    container_name: production-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:

networks:
  app-network:
    driver: bridge