version: '3.8'

services:
  # Tier 1: Frontend
  frontend:
    image: eklakalam/devops-tier3-frontend:latest
    container_name: production-frontend
    restart: always  # If it crashes, restart it
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://<YOUR-EC2-IP>:5000 # Point frontend to backend
    depends_on:
      - backend
    networks:
      - app-network

  # Tier 2: Backend
  backend:
    image: eklakalam/devops-tier3-backend:latest
    container_name: production-backend
    restart: always
    ports:
      - "5000:5000" # Exposed so your Frontend can reach the API
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD} # Reads from .env
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      database:
        condition: service_healthy # Wait until DB is ACTUALLY ready
    networks:
      - app-network

  # Tier 3: Database
  database:
    image: mysql:8.0
    container_name: production-db
    restart: always
    # NOTICE: No 'ports' section here. 
    # The DB is hidden inside the docker network for security.
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    # Healthcheck ensures DB is ready before Backend starts
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:

networks:
  app-network:
    driver: bridge